allowBuilds:
  canvas: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.2.1
  vitest: 4.1.9
minimumReleaseAge: 1440
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
